export const fashionArr = [
  {
    "id": 1,
    "position": 1,
    "src": "/img/Carousel/OUTFIT1.jpg",
    "alt": "item",
  },
  {
    "id": 2,
    "position": 1,
    "src": "/img/Carousel/OUTFIT2.jpg",
    "alt": "item",
  },
  {
    "id": 3,
    "position": 1,
    "src": "/img/Carousel/OUTFIT3.jpg",
    "alt": "item",
  },
  {
    "id": 4,
    "position": 1,
    "src": "/img/Carousel/OUTFIT4.jpg",
    "alt": "item",
  },
  {
    "id": 5,
    "position": 1,
    "src": "/img/Carousel/OUTFIT5.jpg",
    "alt": "item",
  },
  {
    "id": 6,
    "position": 2,
    "src": "/img/Carousel/OUTFIT6.jpg",
    "alt": "item",
  },
  {
    "id": 7,
    "position": 2,
    "src": "/img/Carousel/OUTFIT7.jpg",
    "alt": "item",
  },
  {
    "id": 8,
    "position": 2,
    "src": "/img/Carousel/OUTFIT8.jpg",
    "alt": "item",
  },
  {
    "id": 9,
    "position": 2,
    "src": "/img/Carousel/OUTFIT9.jpg",
    "alt": "item",
  },
  {
    "id": 10,
    "position": 2,
    "src": "/img/Carousel/OUTFIT10.jpg",
    "alt": "item",
  },
  {
    "id": 11,
    "position": 3,
    "src": "/img/Carousel/OUTFIT11.jpg",
    "alt": "item",
  },
  {
    "id": 12,
    "position": 3,
    "src": "/img/Carousel/OUTFIT12.jpg",
    "alt": "item",
  },
  {
    "id": 13,
    "position": 3,
    "src": "/img/Carousel/OUTFIT13.jpg",
    "alt": "item",
  },
  {
    "id": 14,
    "position": 3,
    "src": "/img/Carousel/OUTFIT14.jpg",
    "alt": "item",
  },
  {
    "id": 15,
    "position": 3,
    "src": "/img/Carousel/OUTFIT15.jpg",
    "alt": "item",
  },
  {
    "id": 16,
    "position": 4,
    "src": "/img/Carousel/OUTFIT16.jpg",
    "alt": "item",
  },
  {
    "id": 17,
    "position": 4,
    "src": "/img/Carousel/OUTFIT17.jpg",
    "alt": "item",
  },
  {
    "id": 18,
    "position": 4,
    "src": "/img/Carousel/OUTFIT18.jpg",
    "alt": "item",
  },
  {
    "id": 19,
    "position": 4,
    "src": "/img/Carousel/OUTFIT19.jpg",
    "alt": "item",
  },
  {
    "id": 20,
    "position": 4,
    "src": "/img/Carousel/OUTFIT20.jpg",
    "alt": "item",
  },
]