export const fashionArr = [ 
  {
    "id": 1,
    "position": 1,
    "src": "/img/logo.jpg",
    "alt": "item",
  },
  {
    "id": 2,
    "position": 1,
    "src": "/img/logo.jpg",
    "alt": "item",
  },
  {
    "id": 3,
    "position": 1,
    "src": "/img/logo.jpg",
    "alt": "item",
  },
  {
    "id": 4,
    "position": 1,
    "src": "/img/logo.jpg",
    "alt": "item",
  },
  {
    "id": 5,
    "position": 1,
    "src": "/img/logo.jpg",
    "alt": "item",
  },
  {
    "id": 6,
    "position": 2,
    "src": "/img/mens fashion.jpg",
    "alt": "item",
  },
  {
    "id": 7,
    "position": 2,
    "src": "/img/mens fashion.jpg",
    "alt": "item",
  },
  {
    "id": 8,
    "position": 2,
    "src": "/img/mens fashion.jpg",
    "alt": "item",
  },
  {
    "id": 9,
    "position": 2,
    "src": "/img/mens fashion.jpg",
    "alt": "item",
  },
  {
    "id": 10,
    "position": 2,
    "src": "/img/mens fashion.jpg",
    "alt": "item",
  },
  {
    "id": 11,
    "position": 3,
    "src": "/img/logo.jpg",
    "alt": "item",
  },
  {
    "id": 12,
    "position": 3,
    "src": "/img/logo.jpg",
    "alt": "item",
  },
  {
    "id": 13,
    "position": 3,
    "src": "/img/logo.jpg",
    "alt": "item",
  },
  {
    "id": 14,
    "position": 3,
    "src": "/img/logo.jpg",
    "alt": "item",
  },
  {
    "id": 15,
    "position": 3,
    "src": "/img/logo.jpg",
    "alt": "item",
  },
  {
    "id": 16,
    "position": 4,
    "src": "/img/mens fashion.jpg",
    "alt": "item",
  },
  {
    "id": 17,
    "position": 4,
    "src": "/img/mens fashion.jpg",
    "alt": "item",
  },
  {
    "id": 18,
    "position": 4,
    "src": "/img/mens fashion.jpg",
    "alt": "item",
  },
  {
    "id": 19,
    "position": 4,
    "src": "/img/mens fashion.jpg",
    "alt": "item",
  },
  {
    "id": 20,
    "position": 4,
    "src": "/img/mens fashion.jpg",
    "alt": "item",
  }
]